services:
  archiver:
    build: .
    #image: ghcr.io/lafarer/archiver:latest
    ports:
      - "${ARCHIVER_PORT:-8081}:8080"
    environment:
      ARCHIVER_ANTHROPIC_API_KEY: ${ARCHIVER_ANTHROPIC_API_KEY}
    volumes:
      - ${ARCHIVER_DATA_PATH:-~/Documents/prive}:/data
    restart: unless-stopped
