-- Settings
INSERT INTO setting (key, value) VALUES
    ('watchdog_enabled',     'true'),
    ('ai_model',             'claude-haiku-4-5'),
    ('auto_archive_enabled', 'false'),
    ('confidence_threshold', '0.75'),
    ('import_mode',          'move');

-- Document types
INSERT INTO document_type_def (slug, label, description) VALUES
    -- Finances générales
    ('facture',             'Facture',                          'Facture commerciale pour l''achat de biens ou services. Contient un numéro de facture, une date, un montant TTC et un émetteur.'),
    ('releve-bancaire',     'Relevé bancaire',                  'Relevé de compte bancaire ou d''épargne listant les opérations débit/crédit sur une période.'),
    ('releve-compte',       'Relevé de compte',                 'Relevé mensuel ou trimestriel d''un compte bancaire courant, d''épargne ou d''investissement.'),
    ('releve-epargne',      'Relevé d''épargne / situation de compte', 'Relevé annuel ou semestriel d''un livret d''épargne (Livret A, LDDS, LEP, PEL, CEL) ou d''un compte d''investissement (PEA, compte-titres).'),
    ('virement',            'Avis de virement',                 'Confirmation d''un virement bancaire entrant ou sortant.'),
    ('recu',                'Reçu / Ticket de caisse',          'Justificatif de paiement, ticket de caisse ou reçu émis par un commerçant.'),
    ('ticket-caisse',       'Ticket de caisse / Reçu',          'Ticket de caisse ou reçu de paiement délivré au moment de l''achat, valant preuve d''achat.'),
    ('facture-achat',       'Facture d''achat',                 'Facture détaillée émise par un commerçant ou un site marchand lors de l''achat d''un bien.'),
    ('quittance',           'Quittance',                        'Quittance de loyer ou de paiement attestant la réception d''un règlement.'),
    ('devis',               'Devis',                            'Proposition commerciale détaillant prestations et prix avant commande.'),
    ('bon-de-commande',     'Bon de commande',                  'Document formalisant une commande de biens ou services auprès d''un fournisseur.'),
    ('avoir',               'Avoir / Note de crédit',           'Note de crédit émise par un fournisseur, remboursement partiel ou total d''une facture.'),
    ('tableau-amortissement','Tableau d''amortissement',        'Tableau détaillant le remboursement d''un crédit : échéances, capital remboursé, intérêts, capital restant dû.'),
    -- Impôts et fiscalité
    ('avis-imposition',     'Avis d''imposition',               'Avis d''imposition sur le revenu émis par la Direction Générale des Finances Publiques (DGFiP).'),
    ('declaration-impots',  'Déclaration de revenus (générique)','Formulaire de déclaration annuelle des revenus (2042, 2044…).'),
    ('declaration-revenus', 'Déclaration de revenus',           'Déclaration annuelle des revenus (formulaire 2042 et annexes) déposée auprès de l''administration fiscale.'),
    ('declaration-ifi',     'Déclaration IFI',                  'Déclaration de l''Impôt sur la Fortune Immobilière (IFI), annexée à la déclaration de revenus.'),
    ('avis-ifi',            'Avis IFI',                         'Avis d''imposition relatif à l''Impôt sur la Fortune Immobilière (IFI).'),
    ('droits-succession',   'Droits de succession / donation',  'Document relatif à une déclaration de succession, une donation ou au paiement des droits correspondants.'),
    ('taxe-fonciere',       'Taxe foncière',                    'Avis de taxe foncière pour un bien immobilier.'),
    ('taxe-habitation',     'Taxe d''habitation',               'Avis de taxe d''habitation pour une résidence.'),
    -- Courriers et administratif
    ('courrier-administratif','Courrier administratif',         'Courrier officiel d''un organisme public (CAF, CPAM, Pôle Emploi, mairie, préfecture…).'),
    ('formulaire',          'Formulaire administratif',         'Formulaire à remplir ou déjà complété (Cerfa, demande de prestation…).'),
    -- Contrats et assurances
    ('contrat',             'Contrat',                          'Contrat entre deux parties (service, abonnement, location…).'),
    ('avenant',             'Avenant',                          'Modification ou complément à un contrat existant.'),
    ('attestation-assurance','Attestation d''assurance',        'Attestation prouvant la souscription d''une assurance (auto, habitation, RC…).'),
    ('police-assurance',    'Police d''assurance',              'Contrat d''assurance complet détaillant les garanties, franchises et cotisations.'),
    ('resiliation',         'Résiliation',                      'Lettre ou confirmation de résiliation d''un contrat ou abonnement.'),
    ('garantie',            'Garantie',                         'Certificat ou bon de garantie pour un appareil ou produit acheté.'),
    ('bon-garantie',        'Bon de garantie / Certificat de garantie', 'Document attestant de la garantie constructeur ou légale d''un produit acheté.'),
    ('garantie-etendue',    'Contrat de garantie étendue',      'Contrat souscrit auprès d''un assureur ou d''un distributeur prolongeant la garantie d''origine d''un produit.'),
    -- Santé
    ('ordonnance',          'Ordonnance médicale',              'Prescription médicale d''un médecin pour des médicaments ou actes médicaux.'),
    ('compte-rendu-medical','Compte rendu médical',             'Compte rendu de consultation, d''hospitalisation ou d''examen médical (radio, scanner…).'),
    ('remboursement-sante', 'Remboursement santé',              'Décompte de remboursement de l''Assurance Maladie (CPAM) ou d''une mutuelle.'),
    ('mutuelle',            'Mutuelle / Complémentaire',        'Contrat ou attestation de complémentaire santé (mutuelle).'),
    ('vaccination',         'Carnet de vaccination',            'Attestation ou carnet de vaccination.'),
    ('analyse',             'Résultats d''analyse',             'Résultats d''analyses biologiques, radiologiques ou autres examens.'),
    ('attestation-secu',    'Attestation Sécurité Sociale / Carte Vitale', 'Attestation de droits à l''Assurance Maladie ou document relatif à la carte Vitale.'),
    -- Emploi et revenus
    ('fiche-de-paie',       'Fiche de paie',                   'Bulletin de salaire mensuel. Contient salaire brut, cotisations, net à payer, IBAN et informations employeur.'),
    ('contrat-travail',     'Contrat de travail',               'Contrat d''embauche (CDI, CDD, apprentissage…) ou avenant au contrat.'),
    ('rupture-contrat',     'Rupture de contrat',               'Lettre ou solde de tout compte lié à une rupture conventionnelle, démission ou licenciement.'),
    ('attestation-emploi',  'Attestation employeur / Certificat de travail', 'Attestation de l''employeur, certificat de travail, solde de tout compte, ou attestation Pôle Emploi.'),
    ('attestation-chomage', 'Attestation chômage',              'Attestation d''ouverture de droits ou de versement d''allocations chômage (France Travail).'),
    ('bilan-formation',     'Formation / Certification',        'Attestation de formation professionnelle, bilan de compétences ou certification.'),
    ('notification-retraite','Notification / Relevé de retraite','Notification de droits à la retraite, relevé de carrière, ou bulletin de pension de retraite.'),
    -- Logement
    ('bail',                'Bail / Contrat de location',       'Contrat de location d''un bien immobilier entre un propriétaire et un locataire, incluant ses avenants et renouvellements.'),
    ('etat-des-lieux',      'État des lieux',                   'Document constatant l''état d''un logement à l''entrée ou à la sortie d''un locataire.'),
    ('quittance-loyer',     'Quittance de loyer',               'Reçu mensuel confirmant le paiement du loyer par le locataire.'),
    ('acte-vente',          'Acte de vente immobilier',         'Acte notarié formalisant la vente ou l''achat d''un bien immobilier.'),
    ('acte-notarie',        'Acte notarié',                     'Document établi par un notaire : acte de vente, acte d''achat, donation, hypothèque, compromis de vente.'),
    ('diagnostic',          'Diagnostic (générique)',           'Rapport de diagnostic technique.'),
    ('diagnostic-immobilier','Diagnostic immobilier',           'Diagnostic technique obligatoire d''un bien immobilier : DPE, amiante, plomb, électricité, gaz, termites, ERP, bruit.'),
    ('permis-construire',   'Permis de construire (générique)', 'Autorisation administrative pour des travaux ou constructions.'),
    ('permis-de-construire','Permis de construire / Déclaration de travaux', 'Autorisation administrative pour des travaux de construction, d''extension ou de rénovation.'),
    ('pv-assemblee',        'PV d''assemblée générale (générique)', 'Procès-verbal d''assemblée générale.'),
    ('proces-verbal-ag',    'Procès-verbal d''assemblée générale', 'Compte-rendu d''une assemblée générale de copropriété, incluant les décisions votées et les budgets approuvés.'),
    -- Identité et famille
    ('identite',            'Carte d''identité (générique)',    'Document officiel d''identité nationale ou titre de séjour.'),
    ('carte-identite',      'Carte nationale d''identité',      'Carte nationale d''identité française, recto ou recto-verso.'),
    ('passeport',           'Passeport',                        'Passeport ou document de voyage officiel.'),
    ('diplome',             'Diplôme / Attestation scolaire',   'Diplôme officiel (bac, licence, master…) ou relevé de notes.'),
    ('bulletin-scolaire',   'Bulletin scolaire',                'Bulletin de notes scolaires ou relevé de résultats semestriel ou trimestriel.'),
    ('certificat-scolarite','Certificat de scolarité',          'Attestation d''inscription dans un établissement scolaire ou universitaire pour une année donnée.'),
    ('acte-naissance',      'Acte de naissance',                'Acte de naissance officiel délivré par une mairie ou un consulat.'),
    ('acte-mariage',        'Acte de mariage',                  'Acte de mariage officiel délivré par une mairie.'),
    ('livret-famille',      'Livret de famille',                'Document officiel récapitulant l''état civil d''une famille.'),
    ('jugement',            'Jugement / Décision de justice',   'Décision rendue par un tribunal : jugement de divorce, ordonnance, décision prud''homale, jugement civil.'),
    -- Véhicule
    ('carte-grise',         'Carte grise / Certificat d''immatriculation', 'Document officiel attestant de l''immatriculation d''un véhicule et de l''identité de son propriétaire.'),
    ('controle-technique',  'Contrôle technique',               'Rapport de contrôle technique périodique obligatoire, incluant les points de contrôle, défauts constatés et date de validité.'),
    ('assurance-auto',      'Assurance automobile',             'Contrat ou attestation d''assurance pour un véhicule.'),
    ('facture-reparation',  'Facture de réparation',            'Facture d''un garage ou prestataire pour l''entretien ou la réparation d''un véhicule.'),
    ('constat-amiable',     'Constat amiable',                  'Formulaire rempli entre conducteurs suite à un accident, utilisé pour la déclaration de sinistre auprès des assurances.'),
    ('rapport-expertise',   'Rapport d''expertise véhicule',    'Rapport d''un expert automobile évaluant les dégâts ou la valeur du véhicule, notamment après sinistre.'),
    -- Notices
    ('notice',              'Notice / Manuel d''utilisation',   'Notice d''utilisation, manuel d''installation ou guide de démarrage rapide fourni avec un appareil, un meuble ou un outil.');

-- Tags
INSERT INTO tag_def (slug, label, description) VALUES
    ('eau',           'Eau',                     'Factures et contrats liés à la consommation d''eau.'),
    ('electricite',   'Électricité',             'Factures et contrats d''électricité.'),
    ('gaz',           'Gaz',                     'Factures et contrats de gaz.'),
    ('internet',      'Internet / Box',          'Factures et contrats internet ou téléphone fixe.'),
    ('telephone',     'Téléphone mobile',        'Factures et contrats de téléphonie mobile.'),
    ('logement',      'Logement',                'Documents liés à l''habitation : loyer, charges, copropriété.'),
    ('travaux',       'Travaux',                 'Devis, factures et autorisations de travaux ou rénovation.'),
    ('entretien',     'Entretien',               'Contrats et factures d''entretien (chaudière, climatisation, ascenseur…).'),
    ('reparation',    'Réparation',              'Factures de réparation d''appareils, véhicules ou équipements.'),
    ('electromenager','Électroménager',          'Documents liés aux appareils électroménagers (achat, garantie, réparation).'),
    ('electronique',  'Électronique',            'Documents liés aux appareils électroniques (ordinateur, téléphone, TV…).'),
    ('mobilier',      'Mobilier',                'Documents liés aux meubles et à la décoration intérieure.'),
    ('outillage',     'Outillage',               'Documents liés aux outils, machines et matériel de bricolage.'),
    ('vehicule',      'Véhicule',                'Documents liés aux véhicules : voiture, moto, vélo, scooter.'),
    ('banque',        'Banque',                  'Relevés, virements, prélèvements et documents bancaires.'),
    ('impots',        'Impôts',                  'Déclarations, avis d''imposition et documents fiscaux.'),
    ('assurance',     'Assurance',               'Contrats, attestations, cotisations et remboursements d''assurance.'),
    ('credit',        'Crédit / Prêt',           'Contrats de prêt immobilier ou à la consommation, tableaux d''amortissement.'),
    ('epargne',       'Épargne / Investissement','Relevés de comptes d''épargne, PEA, assurance-vie, livrets.'),
    ('sante',         'Santé',                   'Documents médicaux : ordonnances, comptes rendus, bilans, analyses.'),
    ('mutuelle',      'Mutuelle',                'Documents de complémentaire santé : contrats, décomptes, attestations.'),
    ('famille',       'Famille',                 'Documents d''état civil et actes familiaux (naissance, mariage, divorce…).'),
    ('juridique',     'Juridique',               'Contrats, jugements, décisions de justice et documents légaux.'),
    ('administratif', 'Administratif',           'Courriers et formulaires d''organismes publics (CAF, CPAM, mairie…).'),
    ('sinistre',      'Sinistre',                'Documents liés à un sinistre : déclaration, expertise, remboursement assurance.'),
    ('voyage',        'Voyage',                  'Billets, réservations, hébergements et documents de voyage.'),
    ('abonnement',    'Abonnement',              'Contrats et factures d''abonnements divers (streaming, sport, presse…).');
