INSERT INTO custom_field_def (slug, label, description, field_type) VALUES
    ('montant',        'Montant TTC',                       'Montant total TTC du document (facture, devis, avoir, remboursement, quittance). Extraire la valeur numérique finale due ou remboursée.',                                          'AMOUNT'),
    ('numero_facture', 'Numéro de facture',                 'Numéro ou référence unique de la facture, de l''avoir ou du devis. Souvent libellé "N° facture", "Réf.", "Bon de commande n°".',                                                 'TEXT'),
    ('numero_contrat', 'Numéro de contrat / police',        'Numéro identifiant un contrat ou une police d''assurance. Peut être libellé "N° contrat", "N° police", "Référence contrat", "N° adhérent".',                                     'TEXT'),
    ('date_echeance',  'Date d''échéance',                  'Date d''échéance, de renouvellement ou de fin de validité du contrat, de l''assurance ou de la garantie.',                                                                         'DATE'),
    ('immatriculation','Immatriculation du véhicule',       'Numéro d''immatriculation (plaque) du véhicule concerné par le document (carte grise, contrôle technique, assurance, réparation).',                                                'TEXT'),
    ('adresse_bien',   'Adresse du bien immobilier',        'Adresse complète du bien immobilier concerné (logement loué, bien vendu, bien taxé). Utilisée pour les baux, actes de vente, taxes foncières et diagnostics.',                    'TEXT'),
    ('annee_fiscale',  'Année fiscale',                     'Année fiscale ou d''imposition concernée par le document (avis d''imposition, déclaration de revenus, taxe foncière, taxe d''habitation).',                                       'NUMBER'),
    ('employeur',      'Nom de l''employeur',               'Nom ou raison sociale de l''employeur figurant sur le document (bulletin de salaire, contrat de travail, attestation d''emploi, rupture de contrat).',                            'TEXT'),
    ('medecin',        'Praticien / établissement',         'Nom du médecin prescripteur, du spécialiste ou de l''établissement de soin concerné par l''ordonnance, le compte rendu médical ou les résultats d''analyse.',                    'TEXT'),
    ('numero_dossier', 'Numéro de dossier / référence',     'Numéro de dossier, référence administrative ou identifiant attribué par un organisme public (CAF, CPAM, préfecture, tribunal) pour suivre une demande ou une procédure.',        'TEXT');
